<?xml version="1.0" encoding="utf-8"?><Database Name="Clinic" Class="DataClassesClinicDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-PGOUTHBM\SQLEXPRESS;Initial Catalog=Clinic;Integrated Security=True" SettingsObjectName="DataLayer.Properties.Settings" SettingsPropertyName="Przych_mock_01ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="Id_Pat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PESEL" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Association Name="Patient_Visit" Member="Visits" ThisKey="Id_Pat" OtherKey="Id_Pat" Type="Visit" />
    </Type>
  </Table>
  <Table Name="dbo.Visit" Member="Visits">
    <Type Name="Visit">
      <Column Name="Id_Vis" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Diagnosis" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DT_Reg" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Pat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Doc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Reg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DT_Complete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Patient_Visit" Member="Patient" ThisKey="Id_Pat" OtherKey="Id_Pat" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
</Database>